#!/bin/bash

: ${YEAR_DIR:=2012}
FORM=$1
DATA=$2
FDF=/tmp/output.fdf

node script/apply_values.js ${YEAR_DIR}/definition/${FORM}.json \
	${YEAR_DIR}/transform/${FORM}.json ${DATA} > /tmp/output.fdf

pdftk ${YEAR_DIR}/PDF/${FORM}.pdf fill_form ${FDF} output $3
