#!/bin/bash

YEARDIR=2011
FORM=$1
DATA=$2
FDF=/tmp/output.fdf

node script/apply_values.js ${YEARDIR}/definition/${FORM}.json \
	${YEARDIR}/transform/${FORM}.json ${DATA} > /tmp/output.fdf

pdftk ${YEARDIR}/PDF/${FORM}.pdf fill_form ${FDF} output $3
